<?php

namespace ContainerWWkocVq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yn6zfdTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yn6zfdT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yn6zfdT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'client' => ['privates', 'http_client', 'getHttpClientService', true],
            'headerAuthGenerator' => ['privates', 'App\\Service\\HeaderAuthGenerator', 'getHeaderAuthGeneratorService', true],
        ], [
            'client' => '?',
            'headerAuthGenerator' => 'App\\Service\\HeaderAuthGenerator',
        ]);
    }
}
