<?php

namespace ContainerWWkocVq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EJj7jNBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EJj7jNB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EJj7jNB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuthController::activateAccount' => ['privates', '.service_locator.nWpr6Po', 'get_ServiceLocator_NWpr6PoService', true],
            'App\\Controller\\AuthController::editPassword' => ['privates', '.service_locator.nWpr6Po', 'get_ServiceLocator_NWpr6PoService', true],
            'App\\Controller\\AuthController::getTokenUser' => ['privates', '.service_locator.o2WXrHY', 'get_ServiceLocator_O2WXrHYService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.gPh6X_L', 'get_ServiceLocator_GPh6XLService', true],
            'App\\Controller\\AuthController::resetPassword' => ['privates', '.service_locator.keNhRG9', 'get_ServiceLocator_KeNhRG9Service', true],
            'App\\Controller\\UserController::activateUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController::changeUserPassword' => ['privates', '.service_locator.xlsQoWH', 'get_ServiceLocator_XlsQoWHService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.yn6zfdT', 'get_ServiceLocator_Yn6zfdTService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.cVQrqjh', 'get_ServiceLocator_CVQrqjhService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AuthController:activateAccount' => ['privates', '.service_locator.nWpr6Po', 'get_ServiceLocator_NWpr6PoService', true],
            'App\\Controller\\AuthController:editPassword' => ['privates', '.service_locator.nWpr6Po', 'get_ServiceLocator_NWpr6PoService', true],
            'App\\Controller\\AuthController:getTokenUser' => ['privates', '.service_locator.o2WXrHY', 'get_ServiceLocator_O2WXrHYService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.gPh6X_L', 'get_ServiceLocator_GPh6XLService', true],
            'App\\Controller\\AuthController:resetPassword' => ['privates', '.service_locator.keNhRG9', 'get_ServiceLocator_KeNhRG9Service', true],
            'App\\Controller\\UserController:activateUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\UserController:changeUserPassword' => ['privates', '.service_locator.xlsQoWH', 'get_ServiceLocator_XlsQoWHService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.yn6zfdT', 'get_ServiceLocator_Yn6zfdTService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.cVQrqjh', 'get_ServiceLocator_CVQrqjhService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AuthController::activateAccount' => '?',
            'App\\Controller\\AuthController::editPassword' => '?',
            'App\\Controller\\AuthController::getTokenUser' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\AuthController::resetPassword' => '?',
            'App\\Controller\\UserController::activateUser' => '?',
            'App\\Controller\\UserController::changeUserPassword' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AuthController:activateAccount' => '?',
            'App\\Controller\\AuthController:editPassword' => '?',
            'App\\Controller\\AuthController:getTokenUser' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\AuthController:resetPassword' => '?',
            'App\\Controller\\UserController:activateUser' => '?',
            'App\\Controller\\UserController:changeUserPassword' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
