<?php

namespace ContainerWWkocVq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDirectTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DirectType' shared autowired service.
     *
     * @return \App\Form\DirectType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DirectType.php';

        return $container->privates['App\\Form\\DirectType'] = new \App\Form\DirectType();
    }
}
