<?php

namespace ContainerWWkocVq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFournisseurTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FournisseurType' shared autowired service.
     *
     * @return \App\Form\FournisseurType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FournisseurType.php';

        return $container->privates['App\\Form\\FournisseurType'] = new \App\Form\FournisseurType();
    }
}
