<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWWkocVq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWWkocVq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWWkocVq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWWkocVq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWWkocVq\App_KernelDevDebugContainer([
    'container.build_hash' => 'WWkocVq',
    'container.build_id' => '0ed5a76d',
    'container.build_time' => 1652330618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWWkocVq');
