<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTUPJagG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTUPJagG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTUPJagG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTUPJagG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTUPJagG\App_KernelDevDebugContainer([
    'container.build_hash' => 'TUPJagG',
    'container.build_id' => 'd186a317',
    'container.build_time' => 1652912258,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTUPJagG');
